name: Deploy to Server

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
<<<<<<< HEAD

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 172.232.173.16 >> ~/.ssh/known_hosts
=======
          ssh-keyscan -H 172.232.173.16 >> ~/.ssh/authorized_keys
>>>>>>> 7b608cc05c08592dd3e9c791bb4f6b0fb90b796c

      - name: Test DNS Resolution
        run: nslookup 172.232.173.16

      - name: Test SSH Connectivity
        run: ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@172.232.173.16 "echo 'SSH connection successful'"

      - name: Copy files via SCP
        run: |
          scp -i ~/.ssh/deploy_key -r ./dist root@172.232.173.16:/root/school
