name: Deploy to Server

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 172.232.173.16 >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -i ~/.ssh/deploy_key -r ./dist root@172.232.173.16:/root/school